### PR TITLE
clean: Removed .github/ISSUE_TEMPLATE

### LINKED ISSUE #46: clean: Remove .github/ISSUE_TEMPLATE folder
## Description
As a org contributor,
We need to maintain 1 version of issue templates used in the organization,
so that we can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. 

### Update [Required]
- [ ] [Remove .github/ISSUE_TEMPLATE]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by Aryamanz29**
### Description
Removed `.github/ISSUETEMPLATE`

Fixes #46

### Type of Change:

- Removed existing directory.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] I have written Kotlin Docs whenever is applicable

### CODE REVIEW

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@Aryamanz29 please follow commit message guidelines. 
Also, use the Pull Request Template given in the repository

**Comment by Aryamanz29** [comment]
> @Aryamanz29 please follow commit message guidelines.
> Also, use the Pull Request Template given in the repository

@devkapilbansal  Done requested changes 👍 , I think now it's more relevant 😅

**Comment by Aryamanz29** [comment]
> @Aryamanz29 please follow commit message guidelines.
> Also, use the Pull Request Template given in the repository

@devkapilbansal  Done requested changes 👍 , I think now it's more relevant 😅

**Review by Amulya-coder — CHANGES_REQUESTED** [review]
@Aryamanz29 also updates the link to these files wherever required so that we can't get a 404 errors. Thanks 😊.

**Comment by Aryamanz29** [comment]
@Amulya-coder  Could you check this again?

**Review by Amulya-coder — APPROVED** [review]
Great @Aryamanz29 Thank you for your contribution 🎉🎉

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1: 

@Aryamanz29 thanks for your contribution.

**Comment by isabelcosta** [comment]
@Aryamanz29 thank you for contributing!!
Thank you @devkapilbansal and @Amulya-coder for reviewing this 🤗

**Pull request merged**
