### PR TITLE
Added React.js, html, css, typescript badges

### LINKED ISSUE #59: UI: Add the badge in Readme.md
### Is your feature request related to a problem? Please describe.

I would like if we can have the badges of Tech Stack in the Readme.md . 

##Badges
Badges can be for reactjs , html and other tech-stack used in this project

### PR DESCRIPTION
**Pull request by jaivanti**
### Description

Added React.js, html, css and typescript badges 

Fixes #59

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] I have written Kotlin Docs whenever is applicable

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by khushishikhu** [comment]
@jaivanti  looking good to me. Let other Mentors should also decide

**Review by Rahulm2310 — APPROVED** [review]
@jaivanti just a simple change. Please use the similar style of badges that have been used for existing badges.
Screenshot_2021-04-30-23-18-14

**Comment by jaivanti** [comment]
Editing stem-diverse-tv-cms_README md at master · anitab-org_stem-diverse-tv-cms - Google Chrome 5_1_2021 6_30_24 PM (2)
@Rahulm2310 Will these tags be okay?

**Comment by devkapilbansal** [comment]
> Editing stem-diverse-tv-cms_README md at master · anitab-org_stem-diverse-tv-cms - Google Chrome 5_1_2021 6_30_24 PM (2)
> @Rahulm2310 Will these tags be okay?

@jaivanti Your badges looks good, it is the size that you should try to change

**Comment by Rahulm2310** [comment]
> Editing stem-diverse-tv-cms_README md at master · anitab-org_stem-diverse-tv-cms - Google Chrome 5_1_2021 6_30_24 PM (2)
> @Rahulm2310 Will these tags be okay?

@jaivanti  Looks good now. Thanks 😊

**Comment by jaivanti** [comment]
Please check now @Rahulm2310

**Review by annabauza — APPROVED** [review]

**Pull request merged**
