### PR TITLE
docs : removed table of contents

### LINKED ISSUE #58: Docs: Remove table of contents from the readme.md
### Describe the bug
As now with the GitHub UI, we have a dropdown list for table of contents, we don't need a manual table of contents anymore.

### Expected behavior
Remove the manually added table of contents from the readme.md

### Screenshots
image

image

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

### PR DESCRIPTION
**Pull request by Anmollenka**
### Description

 Removes  the unnecessary table of contents.

Fixes #58 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

There is no table of contents present.
Screenshot from 2021-04-21 19-23-35

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] I have written Kotlin Docs whenever is applicable

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Anmollenka** [comment]
@Amulya-coder @Rahulm2310 Please review my pull request.

**Review by Amulya-coder — APPROVED** [review]
LGTM @Anmollenka 🎉

**Review by Rahulm2310 — APPROVED** [review]
LGTM 💯 🎉

**Review by isabelcosta — APPROVED** [review]
Great contribution @Anmollenka ! thank you!

**Pull request merged**
